'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class referralfeedback
    Public Property feed_feedid As Integer
    Public Property feed_CreatedBy As Nullable(Of Integer)
    Public Property feed_CreatedDate As Nullable(Of Date)
    Public Property feed_UpdatedBy As Nullable(Of Integer)
    Public Property feed_UpdatedDate As Nullable(Of Date)
    Public Property feed_TimeStamp As Nullable(Of Date)
    Public Property feed_Deleted As Nullable(Of Integer)
    Public Property feed_Secterr As Nullable(Of Integer)
    Public Property feed_gpracticeid As Nullable(Of Integer)
    Public Property feed_gpid As Nullable(Of Integer)
    Public Property feed_userid As Nullable(Of Integer)
    Public Property feed_description As String
    Public Property feed_PatientComments As String
    Public Property feed_complications As String
    Public Property feed_ComplicationDetails As String
    Public Property feed_followupdate As Nullable(Of Date)
    Public Property feed_GPComments As String
    Public Property feed_leadid As Nullable(Of Integer)
    Public Property feed_opportunityid As Nullable(Of Integer)
    Public Property feed_feedbackreceived As String
    Public Property feed_feedbackcomments As String
    Public Property feed_expecteddiagnosis As String
    Public Property feed_diagnosiscomments As String
    Public Property EventID As String

End Class
